// <auto-generated />
using System;
using ApiTesourariaAMA.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gerencia_AMA_Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ApiTesourariaAMA.Models.Comprovante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicIdCloudinary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlCloudinary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Comprovantes");
                });

            modelBuilder.Entity("ApiTesourariaAMA.Models.DebitoMembro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComprovanteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoDoacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ComprovanteId");

                    b.HasIndex("TipoDoacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DebitosMembros");
                });

            modelBuilder.Entity("ApiTesourariaAMA.Models.TipoDoacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data_Expiracao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TiposDoacao");
                });

            modelBuilder.Entity("ApiTesourariaAMA.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Perfil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "tesourariaiasdgenibau@gmail.com",
                            Nome = "Billy Grahan",
                            Perfil = 2,
                            Senha = "$2a$11$N7I1fPjZ.x/k4A2/6i4gO.8xW/V7lB7w3KjX7xZ/8m2K2d0f0G1e2"
                        });
                });

            modelBuilder.Entity("ApiTesourariaAMA.Models.DebitoMembro", b =>
                {
                    b.HasOne("ApiTesourariaAMA.Models.Comprovante", "Comprovante")
                        .WithMany()
                        .HasForeignKey("ComprovanteId");

                    b.HasOne("ApiTesourariaAMA.Models.TipoDoacao", "TipoDoacao")
                        .WithMany()
                        .HasForeignKey("TipoDoacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTesourariaAMA.Models.Usuario", "Usuario")
                        .WithMany("Debitos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprovante");

                    b.Navigation("TipoDoacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiTesourariaAMA.Models.Usuario", b =>
                {
                    b.Navigation("Debitos");
                });
#pragma warning restore 612, 618
        }
    }
}
